import Event from 'base/Event';

export default class UiActionEvent extends Event {
}
UiActionEvent.ON_CLOSE_FREE_TRIGGER = 'ON_CLOSE_FREE_TRIGGER';
UiActionEvent.ON_CLOSE_FREE_CONGRATS = 'ON_CLOSE_FREE_CONGRATS';
UiActionEvent.ON_CLOSE_FREE_RETRIGGER = 'ON_CLOSE_FREE_RETRIGGER';
UiActionEvent.ON_BIGWIN_STOP = 'ON_BIGWIN_STOP';
UiActionEvent.ON_HELP_CLOSE = 'ON_HELP_CLOSE';
UiActionEvent.ON_FREE_EARLY_END = 'ON_FREE_EARLY_END';
UiActionEvent.ON_BTN_MORE = 'ON_BTN_MORE';
UiActionEvent.ON_BTN_MORE_CLOSE = 'ON_BTN_MORE_CLOSE';
UiActionEvent.ON_HOME_CLICK = 'ON_HOME_CLICK';
UiActionEvent.ON_CLOSE_JACKPOT_CONGRATS = 'ON_CLOSE_JACKPOT_CONGRATS';
UiActionEvent.ON_MESSAGE_CLOSE = 'ON_MESSAGE_CLOSE';
UiActionEvent.ON_SHOW_JACKPOT_BTN = 'ON_SHOW_JACKPOT_BTN';
UiActionEvent.ON_BTN_MODE = 'ON_BTN_MODE';
UiActionEvent.ON_BTN_MODE_CLOSE = 'ON_BTN_MODE_CLOSE';
UiActionEvent.ON_BTN_BET = 'ON_BTN_BET';
UiActionEvent.ON_BTN_BET_CLOSE = 'ON_BTN_BET_CLOSE';
UiActionEvent.ON_BTN_HIDE_CLOSE = 'ON_BTN_HIDE_CLOSE';
UiActionEvent.ON_SHOW_FREE_HAND = 'ON_SHOW_FREE_HAND';

UiActionEvent.ON_SHOW_MENU = 'ON_SHOW_MENU';
UiActionEvent.ON_SHOW_EXCHANGE = 'ON_SHOW_EXCHANGE';
UiActionEvent.ON_CLOSE_EXCHANGE = 'ON_CLOSE_EXCHANGE';
UiActionEvent.ON_SHOW_CASHOUT = 'ON_SHOW_CASHOUT';
UiActionEvent.ON_CASHOUT_THEN_LEAVE = 'ON_CASHOUT_THEN_LEAVE';
UiActionEvent.ON_CLOSE_CASHOUT = 'ON_CLOSE_CASHOUT';
UiActionEvent.ON_SHOW_SETTING = 'ON_SHOW_SETTING';
UiActionEvent.ON_CLOSE_SETTING = 'ON_CLOSE_SETTING';
UiActionEvent.ON_SHOW_HELP = 'ON_SHOW_HELP';
UiActionEvent.ON_CLOSE_HELP = 'ON_CLOSE_HELP';
